### ISSUE TITLE
Meerdere klassen ondersteunen

### ISSUE THREAD

**Issue by SpaceK33z** [Fontys-Hogeschool-ICT/Pluff#109]
Ondersteuning voor het gebruiken van meerdere klassen.

Stephan hierover:

> Daarnaast is het misschien een idee om in het vakje voor parameters ook “me” ondersteund, want dan kan je je eigen rooster combineren met het rooster van een andere klas.

**Comment by JanOonk** [comment]
Voor de duidelijkheid: meerdere klassen wordt al ondersteund, ik zie bijv. op het Pluff rooster ve student uit S31 ook GD42 staan. De FHICT API /people/groups geeft dit ook terug.
Je bedoelt neem ik aan dat je 2 willekeurige roosters kan combineren: 1 van jezelf (me dus) en 1 van bijv. een vriend uit een andere klas omdat je bijv. een gezamelijk moment wilt prikken.

**Comment by SpaceK33z** [comment]
Al deze klassen wil je natuurlijk niet iedere keer weer opnieuw moeten invullen. Het zou daarom het handigste zijn om een menu item te maken `My timetables`. Hierin zie je een lijstje van zelf samengestelde timetables. Bijvoorbeeld: `me, M50, stage`.

**Comment by svrooij** [comment]
Voorlopig sluit ik deze. Misschien pakken we dat op in een mogelijke nieuwe versie.
