### ISSUE TITLE
Nieuwe icons

### ISSUE THREAD

**Issue by SpaceK33z** [Fontys-Hogeschool-ICT/Pluff#128]
Icons zijn momenteel nog in de oude stijl. Helaas pindakaas ben ik nogal slecht in ontwerpen... Als iemand dit kan maken zou dat tof zijn. In vector aub.

We hebben twee type icons: een 'app icon' (met 'Pluff' uitgeschreven), zie voorbeeld [hier](https://github.com/SpaceK33z/Pluff/blob/master/app/img/apple-touch-icon.png) en een favicon (alleen 'P'), zie voorbeeld [hier](https://raw.githubusercontent.com/SpaceK33z/Pluff/master/app/img/favicon.ico)

**Comment by svrooij** [comment]
Mocht er iemand een nieuw cool logo maken, dat zetten we die er graag in.

**Comment by JortPolderdijk** [comment]
@CasvanDongen designed a new logo for v3 of Pluff.

![Pluff logo](https://cdn.dribbble.com/users/134085/screenshots/3308721/dribbble-pluff_1x.png)
