### ISSUE TITLE
FHICT authenticatie popup opent niet in iOS homescreen app

### ISSUE THREAD

**Issue by SpaceK33z** [Fontys-Hogeschool-ICT/Pluff#214]
Als je Pluff in iOS toevoegt aan het homescreen, en dan op 'Login on Fontys ICT' wilt klikken, gebeurt er niks.

Dit heeft waarschijnlijk te maken met dat `window.open` niet wordt gesupport in deze modus.

**Comment by svrooij** [comment]
Helaas is dit inderdaad niet mogelijk in de App modus. Kunnen we helaas ook niet oplossen, zie #51 en #66
