### ISSUE TITLE
lesweek 5 indicatie springt in volgende week naar calendar week 40

### ISSUE THREAD

**Issue by Fontyschriek** [Fontys-Hogeschool-ICT/Pluff#220]
t/m 'lesweek 5' staat titel 'lesweek x' goed, week daarna wordt er naar 'calender week 40' en verder gesprongen.

**Comment by SpaceK33z** [comment]
Pluff kan alleen maar de lesweken tonen voor weken waarvoor er ook een rooster is.

**Comment by JanOonk** [comment]
In toevoeging hierop: 
-meestal is dit als er vakantie is in die week
-de lesweeknr's worden opgehaald bij de [FHICT API /schedule/weeks](https://api.fhict.nl/swagger/ui/index#!/Schedule/Schedule_Weeks) die deze weer uit een [centrale datalijst](https://portal.fhict.nl/Studentenplein/SitePages/AlleStudenten.aspx) haalt

**Comment by SpaceK33z** [comment]
Dit is niet echt een bug, maar als iemand dit iets netter wil maken is een Pull Request welkom. Ik ben met mijn afstudeerstage bezig dus ik heb zelf geen tijd.
