### ISSUE TITLE
Logischere les tonen bij meerdere lessen

### ISSUE THREAD

**Issue by JanOonk** [Fontys-Hogeschool-ICT/Pluff#222]
Bij meerdere lessen wordt soms een minst logische les getoond. Bijv. in onderstaand voorbeeld als je zoekt op het rooster met vak FUN12: het vak FUN12 wordt door zowel docent ELB als HLGS gegeven op lesuur 1-4. Als je een bepaald rooster toont zoals hieronder kies dan de meest logische, dus niet zo:

![1](https://cloud.githubusercontent.com/assets/13236774/20663631/7c48dc4a-b558-11e6-9b91-82c1f11afa53.PNG)

![2](https://cloud.githubusercontent.com/assets/13236774/20663630/7c417126-b558-11e6-945b-027510d6a0c8.PNG)

maar laat dan OF bij lesuur 1-4 de klas van HLGS zien OF de klas van ELB.

**Comment by SpaceK33z** [comment]
Goed punt. Ik zit nu in mijn afstudeerstage, maar als iemand dit wil oppakken is een Pull Request welkom.

**Comment by hackwerken** [comment]
Ik zet er al een tijdje aan te denken om iets te maken waarmee dubbel geroosterde lessen beter zichtbaar zijn. Het lijkt me handig om de gekleurde vakken dan in tweeën te splitsen zoals dat bijvoorbeeld in Outlook gebeurt.

Dit kost natuurlijk nogal wat tijd, dus of ik er ooit aan ga beginnen...

**Comment by svrooij** [comment]
Dubbel geroosterde lessen kunnen altijd nog beter worden weergegeven, maar ik heb nu op de SQL server een `order by` toegevoegd, waardoor altijd dezelfde volgorde wordt getoond. 

`order by Start` => `order by Start,Docent,Vak` afhankelijk van het op te halen rooster een zinnige sortering gekozen.
