### ISSUE TITLE
Schedule items are not always displayed correctly

### ISSUE THREAD

**Issue by b3nzchr3ur** [Fontys-Hogeschool-ICT/Pluff#231]
At the official version of Fontys rooster the items for PTT2 are shown on Friday morning:
![image](https://cloud.githubusercontent.com/assets/5912368/23848784/085ad882-07d9-11e7-9b25-310ce6b5da69.png)

At the pluff version however the PTT2 items are not shown on Friday morning:
![image](https://cloud.githubusercontent.com/assets/5912368/23848809/216ef1f0-07d9-11e7-8c82-4d9876b20f6e.png)

**Comment by svrooij** [comment]
Dit is geen bug in pluff!

**Comment by b3nzchr3ur** [comment]
Please check out related issue at FHICT-api.
