### ISSUE TITLE
Incorrecte weergave van zelfde lessen maar met verschillend description regel

### ISSUE THREAD

**Issue by JanOonk** [Fontys-Hogeschool-ICT/Pluff#235]
In onderstaande foto's zie je 2 problemen waarvan er 1 reeds een openstaande issue is nl. #222. Het andere probleem is dat als je dezelfde les, d.w.z. dezelfde vak/docent/lokaal/klas combinatie, over meerdere lesuren hebt maar met verschillende description regel (hetgeen wat tussen haakjes staat=3e regel), de description regel van lesuur 2 hetzelfde wordt weergegeven als de description regel van lesuur 1.

In onderstaand voorbeeld zouden eigenlijk de docenten ROE en EGLD op donderdag 2e lesuur proftaakgroep B i.p.v. A moeten beoordelen.

**Weergave in Pluff:**
<img width="138" alt="1" src="https://user-images.githubusercontent.com/13236774/26879074-13a0420e-4b90-11e7-8d88-a96e972f1d0c.PNG">

**Weergave in GP Untis:**
<img width="311" alt="2" src="https://user-images.githubusercontent.com/13236774/26879076-13a7f954-4b90-11e7-9bd9-de82c17f788f.PNG">

**Comment by svrooij** [comment]
The import responsible for merging and formatting lessons wasn't checking the notes field.
Import fixed for lessons where only the notes fields is different (not merged anymore).
