### ISSUE TITLE
Week vooruit resulteert in foute weergave

### ISSUE THREAD

**Issue by samrobben** [Fontys-Hogeschool-ICT/Pluff#239]
Zodra er een week vooruit wordt gekeken in het rooster, kom je uit bij kalenderweek 7, zonder data. Zie foto's.

![image](https://user-images.githubusercontent.com/14262124/35907164-6678e71a-0bed-11e8-9c2e-5078586c0d5d.png)
![image](https://user-images.githubusercontent.com/14262124/35907176-6ce49630-0bed-11e8-84e3-6bc4fb61331e.png)

**Comment by JortPolderdijk** [comment]
Hoi, dat komt omdat volgende week de carnavalsvakantie is. We zijn dan vrij. Daarom is er ook geen rooster beschikbaar die week.

**Comment by samrobben** [comment]
Ah. Mijn fout! Idd. miss handig een melding erin te zetten, aangezien vakanties toch al worden opgehaald.
