### ISSUE TITLE
Pasfotos worden niet (meer) getoond bij docent popup

### ISSUE THREAD

**Issue by JanOonk** [Fontys-Hogeschool-ICT/Pluff#241]
Pasfotos worden niet (meer) getoond bij docent popup.
Als je op de afkorting van de docent klikt krijg je zijn gegevens en foto normaliter.

![bug](https://user-images.githubusercontent.com/13236774/44447946-22d33f00-a5ea-11e8-85a4-7dfc23c11413.PNG)

**Comment by JortPolderdijk** [comment]
Dit is een probleem in de [API](https://api.fhict.nl/) van FHICT. Hier wordt aan gewerkt.

**Comment by JanOonk** [comment]
Het lijkt het weer te doen...
