### ISSUE TITLE
Lessen waar geen docent ingeroosterd staat worden niet weergegeven

### ISSUE THREAD

**Issue by DanielMigchels** [Fontys-Hogeschool-ICT/Pluff#242]
De lessen waar geen docent voor staat ingeroosterd word niet weergegeven op pluff. 
Als er een `-` als docent staat ingevult word hij wel weergegeven.

https://i.imgur.com/IRe2cts.jpg
https://i.imgur.com/UNP8yCU.jpg

Ik zou die les toch graag op mijn rooster hebben.

**Comment by JanOonk** [comment]
De **TXT** export functie van het roosterprogramma GPUntis is gebugged, waardoor lessen zonder docent niet in de .txt dump komen die de API weer gebruikt voor zijn roosterdata. Deze API wordt nl. gebruikt door Pluff voor de roosterinfo en kan daarom deze lessen zonder docenten niet vinden en tonen.
De GPUntis **HTML** export neemt deze lessen echter wel mee en zijn zodoende te zien op https://apps.fhict.nl/roosters/huidigkwartaal
De workaround is dat de roostermaker voor deze lessen de docentcode op "-" zet, waardoor deze _wel_ wordt meegenomen in de export en dus in de API en dus in Pluff. Echter vergeet de roostermaker dit wel eens :(

**Comment by DanielMigchels** [comment]
Bedankt voor de uitleg. Issue closed.
