### ISSUE TITLE
Lessen worden niet weergegeven.

### ISSUE THREAD

**Issue by LordChunk** [Fontys-Hogeschool-ICT/Pluff#243]
Het rooster wordt als leeg weergegeven. Het zelfde geldt voor vakanties.
Lesrooster:
![Lesrooster](https://user-images.githubusercontent.com/23651869/45418141-06c03c00-b684-11e8-91dc-2f94b379b677.png)
Vakantierooster:
![Vakantierooster](https://user-images.githubusercontent.com/23651869/45418195-26576480-b684-11e8-9c67-5418510827ea.png)

**Comment by JortPolderdijk** [comment]
Dit is een probleem in de [API](https://api.fhict.nl/) van FHICT. Ik zal er even achteraan gaan!

**Comment by JortPolderdijk** [comment]
Inmiddels is het weer gefixt!
